#include "main.h"
int main(void){
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
	GPIOB->MODER |= GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER7_0 | GPIO_MODER_MODER6_0  | GPIO_MODER_MODER5_0 | GPIO_MODER_MODER4_0|  GPIO_MODER_MODER3_0 | GPIO_MODER_MODER8_0;
	GPIOB->ODR |=0x1ff;
}

